# Generated by Django 4.2.3 on 2023-07-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
    ]
